// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-XUyRaDmaZtkbpRNMe3DkkGq9FctT4U',
    appId: '1:117449274889:web:58b63e454cefa432396ad8',
    messagingSenderId: '117449274889',
    projectId: 'pdahospitality-7dfa0',
    authDomain: 'pdahospitality-7dfa0.firebaseapp.com',
    storageBucket: 'pdahospitality-7dfa0.appspot.com',
    measurementId: 'G-BYLD0LSVPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAReJE6Tn637NPiwACXj1RTGhH3uT9CZm0',
    appId: '1:117449274889:android:22e70f267ab5844d396ad8',
    messagingSenderId: '117449274889',
    projectId: 'pdahospitality-7dfa0',
    storageBucket: 'pdahospitality-7dfa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbDUl9BRGZImpmBTEOlSm3mVlf3_ltIgU',
    appId: '1:117449274889:ios:d475d74ae2e6d9a1396ad8',
    messagingSenderId: '117449274889',
    projectId: 'pdahospitality-7dfa0',
    storageBucket: 'pdahospitality-7dfa0.appspot.com',
    androidClientId: '117449274889-njn2e91860ce2ve8f55rhm85pq0k816f.apps.googleusercontent.com',
    iosClientId: '117449274889-5mlkpo4c38704ebifmiuf4lu4lqno84f.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbDUl9BRGZImpmBTEOlSm3mVlf3_ltIgU',
    appId: '1:117449274889:ios:d475d74ae2e6d9a1396ad8',
    messagingSenderId: '117449274889',
    projectId: 'pdahospitality-7dfa0',
    storageBucket: 'pdahospitality-7dfa0.appspot.com',
    androidClientId: '117449274889-njn2e91860ce2ve8f55rhm85pq0k816f.apps.googleusercontent.com',
    iosClientId: '117449274889-5mlkpo4c38704ebifmiuf4lu4lqno84f.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurante',
  );
}
